import { ChatAIResponse, ChatCard, ChatMessage } from "./chat-contracts";

export const prdV6ChatCardFixtures: ChatCard[] = [
  {
    id: "basketball-calendar",
    kind: "calendar_draft",
    icon: "calendar",
    typeLabel: "Calendar draft",
    title: "Basketball game",
    body: "A draft event is ready for Leo's Friday game.",
    metadata: ["Friday", "5:30 PM", "Leo"],
    action: { label: "Review event", intent: "review" },
    event: {
      person: "leo",
      dateLabel: "Friday",
      timeLabel: "5:30 PM",
      location: "Gym",
    },
  },
  {
    id: "water-bottle-reminder",
    kind: "reminder",
    icon: "bell",
    typeLabel: "Reminder",
    title: "Bring water bottle",
    body: "A reminder can go off before everyone leaves.",
    metadata: ["Friday", "4:30 PM"],
    action: { label: "Edit", intent: "edit" },
    reminder: {
      dueLabel: "Friday at 4:30 PM",
      assignee: "family",
    },
  },
  {
    id: "baby-feed-log",
    kind: "baby_log",
    icon: "bottle",
    typeLabel: "Baby log",
    title: "Baby may be ready to feed",
    body: "The last feed was 2h 45m ago.",
    metadata: ["Last feed 2h 45m ago", "Suggested by Nora"],
    action: { label: "Log feed", intent: "log" },
    babyLog: {
      baby: "baby",
      lastFeedLabel: "2h 45m ago",
      suggestedAction: "feed",
    },
  },
  {
    id: "piano-lesson-recap",
    kind: "lesson_recap",
    icon: "music",
    typeLabel: "Lesson recap",
    title: "Lesson recap",
    body: "Teacher notes and the video are condensed into a short plan.",
    metadata: ["Teacher notes", "12s demo", "practice plan"],
    action: { label: "View recap", intent: "view" },
    recap: {
      child: "sophie",
      sourceLabel: "Piano video",
      steps: ["Warm up hands", "Practice left hand", "Play slowly twice"],
    },
  },
  {
    id: "soccer-memory",
    kind: "memory",
    icon: "soccer",
    typeLabel: "Memory",
    title: "Soccer time backyard",
    body: "Leo scored twice and laughed non-stop.",
    metadata: ["Auri Robot", "Today 4:20 PM", "Leo"],
    action: { label: "View", intent: "view" },
    memory: {
      sourceType: "auri",
      capturedAtLabel: "Today 4:20 PM",
      people: ["leo"],
    },
  },
  {
    id: "grandma-story-draft",
    kind: "story_draft",
    icon: "photos",
    typeLabel: "Story draft",
    title: "Grandma update draft",
    body: "A warm Sunday note with clips, photos, and a short caption.",
    metadata: ["2 clips", "14 photos", "warm caption"],
    action: { label: "Open draft", intent: "open" },
    story: {
      audience: "grandma",
      sourceCount: 16,
      tone: "warm",
    },
  },
  {
    id: "pickup-text-dad",
    kind: "text",
    icon: "person",
    typeLabel: "Text",
    title: "Pickup: Dad",
    body: "Drafted a confirmation message for the family thread.",
    metadata: ["Leo", "Dad", "Ready to send"],
    text: {
      recipient: "family",
      draftText: "Dad will pick up Leo after basketball.",
      context: "Basketball pickup",
    },
  },
];

const cardById = Object.fromEntries(prdV6ChatCardFixtures.map((card) => [card.id, card])) as Record<string, ChatCard>;

export const chatFixtureMessages: ChatMessage[] = [
  {
    id: "mom-basketball",
    role: "user",
    sender: "Mom",
    avatar: "mom",
    timeLabel: "9:12 AM",
    text: "Leo has basketball Friday at 5:30. Bring water bottle.",
  },
  {
    id: "nora-basketball",
    role: "helper",
    sender: "Nora",
    avatar: "nora",
    timeLabel: "9:13 AM",
    text: "I created a calendar draft and a reminder.",
    cards: [
      cardById["basketball-calendar"],
      cardById["water-bottle-reminder"],
    ],
  },
  {
    id: "mom-baby-feed",
    role: "user",
    sender: "Mom",
    avatar: "mom",
    timeLabel: "9:14 AM",
    text: "Can you check the baby feed timing?",
  },
  {
    id: "nora-baby-feed",
    role: "helper",
    sender: "Nora",
    avatar: "nora",
    timeLabel: "9:14 AM",
    text: "Baby may be ready to feed. I prepared a quick log action.",
    cards: [cardById["baby-feed-log"]],
  },
  {
    id: "dad-pickup",
    role: "user",
    sender: "Dad",
    avatar: "dad",
    timeLabel: "9:15 AM",
    text: "I can take Leo.",
  },
  {
    id: "nora-pickup",
    role: "helper",
    sender: "Nora",
    avatar: "nora",
    timeLabel: "9:15 AM",
    text: "Got it. I added Dad as pickup.",
    cards: [cardById["pickup-text-dad"]],
  },
  {
    id: "mom-piano",
    role: "user",
    sender: "Mom",
    avatar: "mom",
    timeLabel: "9:18 AM",
    text: "Here's Sophie's piano lesson video.",
  },
  {
    id: "milo-piano",
    role: "helper",
    sender: "Milo",
    avatar: "milo",
    timeLabel: "9:19 AM",
    text: "I summarized the lesson recording and pulled out 3 tiny practice steps.",
    cards: [cardById["piano-lesson-recap"]],
  },
  {
    id: "mom-grandma",
    role: "user",
    sender: "Mom",
    avatar: "mom",
    timeLabel: "9:24 AM",
    text: "Make a Sunday update for Grandma.",
  },
  {
    id: "mira-grandma",
    role: "helper",
    sender: "Mira",
    avatar: "mira",
    timeLabel: "9:25 AM",
    text: "I found 2 Auri Robot clips and 14 phone photos. I made a warm draft for Sunday.",
    cards: [cardById["grandma-story-draft"]],
  },
  {
    id: "mira-memory",
    role: "helper",
    sender: "Mira",
    avatar: "mira",
    timeLabel: "9:28 AM",
    text: "I also saved the backyard soccer clip into Memory.",
    cards: [cardById["soccer-memory"]],
  },
];

export const chatAIResponseFixtures: ChatAIResponse[] = chatFixtureMessages
  .filter((message) => message.role === "helper" && message.cards?.length)
  .map((message) => ({
    id: `${message.id}-response`,
    createdAt: "2026-06-10T09:30:00.000Z",
    threadId: "sophies-family",
    helper: message.sender as ChatAIResponse["helper"],
    message,
    cards: message.cards ?? [],
    suggestedReplies: ["Looks good", "Make it shorter", "Show details"],
  }));
