import { ChatAIResponse, ChatCard, ChatMessage } from "./chat-contracts";

// The family group = the task board. This mirrors the canonical group-chat
// story from the AURI product site: Mom/Dad plus the in-group teammates
// Reminder (keeper), Cameraman (the eye), Companion (reads).
export const prdV6ChatCardFixtures: ChatCard[] = [
  {
    id: "sophie-watch-plan",
    kind: "job",
    icon: "camera-note",
    typeLabel: "Cameraman plan",
    title: "Watch for Sophie's best moments",
    body: "A light watch-and-film plan for today.",
    metadata: ["Cameraman", "Today", "Sophie", "Created"],
    plan: [
      "Look for Sophie every 15 minutes today.",
      "If she's in view, film while she stays in frame.",
      "Stop when she leaves the frame.",
      "Cut the best moments into a short highlight.",
    ],
    autoAdvanceSubtasks: false,
    subtasks: [
      { label: "Created today's watch-and-film plan", state: "done", timeLabel: "9:02" },
      { label: "Next check for Sophie", state: "todo", timeLabel: "9:15" },
      { label: "Film when Sophie is in view", state: "todo" },
      { label: "Edit the best moments", state: "todo" },
    ],
  },
  {
    id: "sophie-watch-checking",
    kind: "job",
    icon: "camera-note",
    typeLabel: "Cameraman running",
    title: "Looking for Sophie",
    metadata: ["Cameraman", "Every 15 min", "Running"],
    autoAdvanceSubtasks: false,
    subtasks: [
      { label: "9:15 check - Sophie not in view", state: "done" },
      { label: "9:30 check - looking again", state: "active", timeLabel: "now" },
      { label: "Film when Sophie is in view", state: "todo" },
      { label: "Review clips", state: "todo" },
    ],
  },
  {
    id: "sophie-watch-filming",
    kind: "job",
    icon: "camera-note",
    typeLabel: "Cameraman running",
    title: "Filming Sophie",
    metadata: ["Cameraman", "Sophie in view", "Recording"],
    autoAdvanceSubtasks: false,
    subtasks: [
      { label: "9:15 check - Sophie not in view", state: "done" },
      { label: "9:30 check - Sophie found in the living room", state: "done" },
      { label: "Filming while she stays in frame", state: "active", timeLabel: "now" },
      { label: "Cut the best moments", state: "todo" },
    ],
  },
  {
    id: "sophie-first-steps-film",
    kind: "memory",
    icon: "camera-note",
    typeLabel: "Highlight film",
    title: "Sophie's first steps",
    body: "A short highlight from today's watch-and-film plan.",
    metadata: ["Cameraman", "0:12", "Sophie"],
    videoUrl: "/demo-media/e82d1f82-ca73-4222-8db0-4fe4799b9f04.mp4",
    poster: "/demo-media/7fada8f9-fc26-417f-86c7-80fd6b3048b8.jpg",
    durationLabel: "0:12",
    memory: {
      sourceType: "auri",
      capturedAtLabel: "Today 9:42 AM",
      people: ["mia"],
    },
  },
  {
    id: "medicine-receipt",
    kind: "memory",
    icon: "video-heart",
    typeLabel: "Video receipt",
    title: "Medicine taken · 2:04 PM",
    body: "A 6-second video receipt confirms Mia’s 2pm dose.",
    metadata: ["Auri Robot", "0:06", "Mia"],
    videoUrl: "/demo-media/67fd7e14-aaab-4092-9b9c-1091ec2f87b7.mp4",
    poster: "/demo-media/77128c23-7216-4012-aaea-2a8c21e74de5.jpg",
    durationLabel: "0:06",
    memory: {
      sourceType: "auri",
      capturedAtLabel: "Today 2:04 PM",
      people: ["mia"],
    },
  },
  {
    id: "first-steps-film",
    kind: "memory",
    icon: "camera-note",
    typeLabel: "Film",
    title: "She walked!",
    body: "Three steps to the couch — a 30-second film, sent to the group.",
    metadata: ["Auri Robot", "0:30", "Mia"],
    videoUrl: "/demo-media/e82d1f82-ca73-4222-8db0-4fe4799b9f04.mp4",
    poster: "/demo-media/7fada8f9-fc26-417f-86c7-80fd6b3048b8.jpg",
    durationLabel: "0:30",
    memory: {
      sourceType: "auri",
      capturedAtLabel: "Today 5:12 PM",
      people: ["mia"],
    },
  },
  {
    id: "checkup-calendar",
    kind: "job",
    icon: "calendar",
    typeLabel: "Calendar event",
    title: "Leo’s checkup",
    metadata: ["Tomorrow", "9:30 AM", "Leo"],
    action: { label: "Review event", intent: "review" },
  },
  {
    id: "morning-routine",
    kind: "job",
    icon: "backpack",
    typeLabel: "Routine",
    title: "Leaving for school",
    metadata: ["Leo", "weekday mornings"],
    subtasks: [
      { label: "Water bottle in bag", state: "done", timeLabel: "7:31" },
      { label: "Fruit packed", state: "active", timeLabel: "now" },
      { label: "Shoes on", state: "todo" },
      { label: "Coat", state: "todo" },
    ],
  },
  {
    id: "reading-moment",
    kind: "memory",
    icon: "book",
    typeLabel: "Reading moment",
    title: "Goodnight Moon with Companion",
    body: "Mia asked where the mouse went 🐭",
    metadata: ["Reading", "Tonight", "Mia"],
    action: { label: "View", intent: "view" },
    memory: {
      sourceType: "reading",
      capturedAtLabel: "Tonight",
      people: ["mia"],
    },
  },
];

const cardById = Object.fromEntries(prdV6ChatCardFixtures.map((card) => [card.id, card])) as Record<string, ChatCard>;

export const chatFixtureMessages: ChatMessage[] = [
  {
    id: "mom-sophie-watch",
    role: "user",
    sender: "Mom",
    avatar: "mom",
    timeLabel: "9:02 AM",
    text: "Watch for Sophie's best moments today.",
  },
  {
    id: "cameraman-sophie-plan",
    role: "helper",
    sender: "Cameraman",
    avatar: "cameraman",
    timeLabel: "9:02 AM",
    text: "Got it. I'll check every 15 minutes and film when Sophie is in view.",
    cards: [cardById["sophie-watch-plan"]],
  },
  {
    id: "cameraman-sophie-checking",
    role: "helper",
    sender: "Cameraman",
    avatar: "cameraman",
    timeLabel: "9:30 AM",
    text: "I checked in once and did not see Sophie. I'm looking again now.",
    cards: [cardById["sophie-watch-checking"]],
  },
  {
    id: "cameraman-sophie-filming",
    role: "helper",
    sender: "Cameraman",
    avatar: "cameraman",
    timeLabel: "9:36 AM",
    text: "Found her in the living room. I'm filming while she stays in frame.",
    cards: [cardById["sophie-watch-filming"]],
  },
  {
    id: "cameraman-sophie-done",
    role: "helper",
    sender: "Cameraman",
    avatar: "cameraman",
    timeLabel: "9:42 AM",
    text: "Found a keeper - Sophie took a few steps toward the couch. I cut it into a short highlight.",
    cards: [cardById["sophie-first-steps-film"]],
  },
  {
    id: "mom-meds",
    role: "user",
    sender: "Mom",
    avatar: "mom",
    timeLabel: "2:02 PM",
    text: "Did Mia take her 2pm meds?",
  },
  {
    id: "homekeeper-meds",
    role: "helper",
    sender: "Reminder",
    avatar: "homekeeper",
    timeLabel: "2:04 PM",
    text: "Yes — 2:04 PM. ✓",
    cards: [cardById["medicine-receipt"]],
  },
  {
    id: "dad-film",
    role: "user",
    sender: "Dad",
    avatar: "dad",
    timeLabel: "4:58 PM",
    text: "Film her if she does something today 🙏",
  },
  {
    id: "cameraman-film",
    role: "helper",
    sender: "Cameraman",
    avatar: "cameraman",
    timeLabel: "5:12 PM",
    text: "She walked! 🎉 Three steps to the couch.",
    cards: [cardById["first-steps-film"]],
  },
  {
    id: "mom-react",
    role: "user",
    sender: "Mom",
    avatar: "mom",
    timeLabel: "5:13 PM",
    text: "AHHH 😭 watching now",
  },
  {
    id: "homekeeper-checkup",
    role: "helper",
    sender: "Reminder",
    avatar: "homekeeper",
    timeLabel: "5:20 PM",
    text: "📅 Leo’s checkup tomorrow, 9:30 AM — added to your calendar.",
    cards: [cardById["checkup-calendar"]],
  },
  {
    id: "companion-reading",
    role: "helper",
    sender: "Companion",
    avatar: "companion",
    timeLabel: "8:10 PM",
    text: "Mia and I read Goodnight Moon — she asked where the mouse went 🐭",
    cards: [cardById["reading-moment"]],
  },
  {
    id: "homekeeper-routine",
    role: "helper",
    sender: "Reminder",
    avatar: "homekeeper",
    timeLabel: "7:33 AM",
    text: "On it — walking Leo through the morning routine.",
    cards: [cardById["morning-routine"]],
  },
];

export const chatAIResponseFixtures: ChatAIResponse[] = chatFixtureMessages
  .filter((message) => message.role === "helper" && message.cards?.length)
  .map((message) => ({
    id: `${message.id}-response`,
    createdAt: "2026-06-18T09:30:00.000Z",
    threadId: "janes-family",
    helper: message.sender as ChatAIResponse["helper"],
    message,
    cards: message.cards ?? [],
    suggestedReplies: ["Looks good", "Make it shorter", "Show details"],
  }));
